### ISSUE TITLE
Valid parsed workflow cannot be unmarshalled after being marshalled to JSON

### ISSUE THREAD

**Issue by obloquy** [serverlessworkflow/sdk-go#110]
**What happened**: I'm working on integrating serverlessworkflow and Temporal and using the current main branch of the serverlessworkflow sdk (b9db1ddbffb2). I'm trying to pass a parsed serverlessworkflow to a Temporal workflow. This leads the Temporal SDK to go through a marshal/unmarshal cycle which fails to unmarshal some recent Auth def changes in the serverlessworkflow.

**What you expected to happen**: I would expect the marshal/unmarshal to work as it did for the serverlessworkflow 2.1.2 release

**How to reproduce it**: Reproduce with the attached source which doesn't require temporal.
[main.go.gz](https://github.com/serverlessworkflow/sdk-go/files/9830571/main.go.gz)

**Anything else we need to know?**:

**Environment**:
- Specification version used: latest (serverlessworkflow sdk commit b9db1ddbffb2)

- Go version: go version go1.17.11 darwin/amd64

**Comment by ricardozanini** [comment]
@lsytj0413 @spolti, can you guys take a look, please? Might be related to the recent changes.

**Comment by spolti** [comment]
hi, the referred pr fixes the issue, please validate.

**Comment by obloquy** [comment]
Cheers. Thanks for the quick turnaround. I can confirm the issue is resolved by #111
