### ISSUE TITLE
Change the root path of not absolute import file 

### ISSUE THREAD

**Issue by lsytj0413** [serverlessworkflow/sdk-go#114]
**What would you like to be added**:

**Why is this needed**:

- https://github.com/serverlessworkflow/sdk-go/pull/100#discussion_r991328194

**Comment by spolti** [comment]
Hi. @lsytj0413, can you please add more details about this enhancement?

Thanks :)

**Comment by lsytj0413** [comment]
> Hi. @lsytj0413, can you please add more details about this enhancement?
> 
> Thanks :)

I have add the links to a previous comment. Currently the parser will locate import file (with not absolute path) joined the current working directory, this will base on the executable file's path.

So i proposed to add an `Include` options, user can use the to change the import file base directory.
