### ISSUE TITLE
Add Prow bot style tool to automate PR/Issue workflow

### ISSUE THREAD

**Issue by lsytj0413** [serverlessworkflow/sdk-go#115]
**What would you like to be added**:

- use https://github.com/kubernetes/test-infra/tree/master/prow style tool to automate  `PR merging` and other job.

**Why is this needed**:

**Comment by lsytj0413** [comment]
Perhaps https://github.com/jpmcb/prow-github-actions/issues is helpful.

**Comment by ricardozanini** [comment]
That would be awesome. I believe I also have a new issue related to this one to include checks against the spec's scheme in the CI too.

**Comment by lsytj0413** [comment]
> 

Can you explain a little more, I'm not very clear what you mean.

**Comment by ricardozanini** [comment]
The idea is to download the scheme/examples from the main repo (https://github.com/serverlessworkflow/specification) and include specific integration tests with those assets.

**Comment by lsytj0413** [comment]
> The idea is to download the scheme/examples from the main repo (https://github.com/serverlessworkflow/specification) and include specific integration tests with those assets.

The most problem is the example have been embedded in `README.md` file's content, in order to archive this goal, we should move example's schema file to another separate directory.

**Comment by spolti** [comment]
This is a valid improvement.

**Comment by lsytj0413** [comment]
> > The idea is to download the scheme/examples from the main repo (https://github.com/serverlessworkflow/specification) and include specific integration tests with those assets.
> 
> The most problem is the example have been embedded in `README.md` file's content, in order to archive this goal, we should move example's schema file to another separate directory.

https://github.com/serverlessworkflow/specification/issues/324 is doing this.
