### ISSUE TITLE
Implement `FromYAMLSource`  function on parser package to have same functionality as the JSON parser function

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/sdk-go#15]
**What would you like to be added**:

When clients know beforehand that their content is in YAML format, would make a lot of sense having this shortcut in the `parser` package. The code is already there, should be a super easy implementation.

**Why is this needed**:
Enhance the user experience.

**Comment by iwita** [comment]
Hello, I am a total newbie in open-source contributing.
Could I get that issue assigned?

**Comment by ricardozanini** [comment]
Hello @iwita ! Welcome!

Please, just go ahead, fork this repo and send a PR :+1: 

If you have any questions, please reach out to me at `#serverless-workflow` channel in [CNCF slack](cloud-native.slack.com).

**Comment by ricardozanini** [comment]
For some reason, I've filed this issue in a moment of a collapsed brain. It's there since the beginning: https://github.com/serverlessworkflow/sdk-go/blob/master/parser/parser.go#L36-L42

@iwita thanks for pointing this out, I'll close this issue for now and will review our roadmap for more things to be done and will let you know.

Thanks again for this contribution! :)
