### ISSUE TITLE
Improve validation

### ISSUE THREAD

**Issue by ribeiromiranda** [serverlessworkflow/sdk-go#153]
**What would you like to be added**:
Improve the following validations:
* Mutually exclusive parameters:
  *  "transition and end properties are mutually exclusive, meaning that you cannot define both of them at the same time."
  * workflow `id` and `key`
  * ...
* Exists the `events`, `functions` that the state/action references
* Exist `start`, `transition`, and `compensatedBy` states
* State recursive
* ...

**Why is this needed**:
Avoid applications using the SDK to do this validation.

**Comment by ricardozanini** [comment]
@ribeiromiranda we are looking for contributions to add these validations to the SDK. Are you willing to send a PR?

**Comment by ricardozanini** [comment]
Yes.

![image](https://user-images.githubusercontent.com/1538000/223720169-fbf582c4-2ed3-47fa-847c-c9c54a1c7bcb.png)
