### ISSUE TITLE
Validate the kubebuilder annotations to make sure it is generating a valid OpenAPI structure.

### ISSUE THREAD

**Issue by spolti** [serverlessworkflow/sdk-go#161]
**What would you like to be added**:
Need to find a way to generated and validate the CSV with the kubebuilder annotations to make sure that the generated CSV is compliance with the OpenAPI required by Kubernetes.

One option to validate would be using something like:

```
kustomize build config/crd | kubectl apply -f -
```

**Why is this needed**:

**Comment by ricardozanini** [comment]
That means our CI needs to instantiate either KIND or Minikube, right?

**Comment by spolti** [comment]
probably, idk yet.
there must be another way.
