### ISSUE TITLE
Revisit Workflow.Auth struct , can it be just Auths instead AuthArray

### ISSUE THREAD

**Issue by spolti** [serverlessworkflow/sdk-go#162]
**What would you like to be added**:
Today we have:

```
type BaseWorkflow struct {
...
	Auth AuthArray `json:"auth,omitempty" validate:"omitempty"`
}

...

type AuthArray []Auth

func (r *AuthArray) UnmarshalJSON(data []byte) error {
	if len(data) == 0 {
		return fmt.Errorf("no bytes to unmarshal")
	}

	switch data[0] {
	case '"':
		return r.unmarshalFile(data)
	case '[':
		return r.unmarshalMany(data)
	}

	return fmt.Errorf("auth value '%s' is not supported, it must be an array or string", string(data))
}

```

Validate if it can be resumed to:
```
type BaseWorkflow struct {
...
	Auth []Auth `json:"auth,omitempty" validate:"omitempty"`
}
```

**Why is this needed**:

**Comment by lsytj0413** [comment]
We define a `AuthArray` type because we want to support the `auth` field which have two type:

- string
- array of object

If we just use `[]Auth`, we must do this in BaseWorkflow unmarshal method.

**Comment by ricardozanini** [comment]
I think this PR (#159) addresses this issue.

**Comment by spolti** [comment]
Partially I guess, it still as `Auth AuthArray `json:"auth,omitempty" validate:"omitempty"`

but the problem as the Unmarshall func, that it is simpler now. 
Maybe we can resolve it when  https://github.com/serverlessworkflow/sdk-go/pull/159 is merged.

**Comment by ribeiromiranda** [comment]
To define the `UnmarshalJSON` method, it is necessary to define the `AuthArray` type, so as @lsytj0413 has explained https://github.com/serverlessworkflow/sdk-go/issues/162#issuecomment-1471146282.

Two example patterns of [unmarshal](https://gist.github.com/ribeiromiranda/8931e27bb8d3edcc638518e284279d7b).
The PR #159 is the pattern 1.


Other question, the naming pattern for array is use plural to represent. For example:
* `type Functions []Function`
* `type Events []Event`

Can rename from `type AuthArray []Auth` to `type Auhtorizations []Auth`?

**Comment by ricardozanini** [comment]
> To define the `UnmarshalJSON` method, it is necessary to define the `AuthArray` type, so as @lsytj0413 has explained [#162 (comment)](https://github.com/serverlessworkflow/sdk-go/issues/162#issuecomment-1471146282).
> 
> Two example patterns of [unmarshal](https://gist.github.com/ribeiromiranda/8931e27bb8d3edcc638518e284279d7b). The PR #159 is the pattern 1.
> 
> Other question, the naming pattern for array is use plural to represent. For example:
> 
> * `type Functions []Function`
> * `type Events []Event`
> 
> Can rename from `type AuthArray []Auth` to `type Auhtorizations []Auth`?

Simply `Auths` should do. 
Thank you!

**Comment by spolti** [comment]
fixed as part of https://github.com/serverlessworkflow/sdk-go/pull/159
