### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by hongliang5316** [serverlessworkflow/sdk-go#165]
**What is the question**:

Have any plans to do the following 2 abilities? like `sdk-java`

`Generate workflow diagram (SVG)`

`Set of utilities to help runtimes interpret the Serverless Workflow object model
 `

**Comment by spolti** [comment]
Hi @hongliang5316, thanks for the question.
For:

- Generate workflow diagram (SVG)
Yes, it is in the roadmap, but there is no ETA yet, please take a look here: https://github.com/serverlessworkflow/sdk-go

About the second question, can you please elaborate? What kind of help utilities are you looking for in specific?



Thanks.
