### ISSUE TITLE
Use of external resource ("functions", "events", etc) analysis of the specification v0.8

### ISSUE THREAD

**Issue by ribeiromiranda** [serverlessworkflow/sdk-go#168]
The specification has the definition below which is different from the example:

> The functions property can be either an in-line [function](https://github.com/serverlessworkflow/specification/blob/0.8.x/specification.md#Function-Definition) definition array, or an URI reference to a resource containing an array of [functions](https://github.com/serverlessworkflow/specification/blob/0.8.x/specification.md#Function-Definition) definition. Referenced resource can be used by multiple workflow definitions.

Especification example
```json
{
   "functions": [
      {
         "name":"HelloWorldFunction",
         "operation":"file://myapi.json#helloWorld"
      }
   ]
}
```

My interpretation about the specification, the [sdk-net function definitions resource](https://github.com/serverlessworkflow/sdk-net/blob/main/src/ServerlessWorkflow.Sdk.UnitTests/Resources/functions/petstore.json) also use that
```json
[
    {
       "name":"HelloWorldFunction",
       "operation":"file://myapi.json#helloWorld"
    }
 ]
```

My question which definition is correct? Should we define one of them or use both?

**Comment by spolti** [comment]
IMHO the second option is a JSON anti-pattern, when unmarshaling we would need to guess which struct to use.
my 2 cents:

```
{
   "functions": [
      {
         "name":"HelloWorldFunction",
         "operation":"file://myapi.json#helloWorld"
      }
   ]
}
```

and 

```
{
   "functions": filr:///functions.yaml
}
```

this way we are compliant with the spec and it is clearer on which struct it is defining.

**Comment by ribeiromiranda** [comment]
Issue closed because there are other discussions on the topic:

https://github.com/serverlessworkflow/specification/issues/691
https://github.com/serverlessworkflow/specification/issues/676
https://github.com/serverlessworkflow/specification/pull/701

Due to the discussions and for the purpose of PR: #159 I agree with:
```
{
    "functions": [
       {
          "name":"HelloWorldFunction",
          "operation":"myapi.json#helloWorld"
       }
    ]
}
```
