### ISSUE TITLE
Eventstate does not default the 'exclusive' field to true.

### ISSUE THREAD

**Issue by alankm** [serverlessworkflow/sdk-go#17]
**What happened**:

Unmarshaling a workflow with an Event state that has an unspecified 'exclusive' field. The value for the field is 'false'.

**What you expected to happen**:

The spec states that the default value for 'exclusive' should be 'true'.

**Anything else we need to know?**:

If a key is missing in JSON Go will unmarshal it to the type's default value. The default value for a boolean in Go is false. To fix this you could either change the field to a pointer to a bool or write a custom json unmarshaler for the struct.

**Comment by ricardozanini** [comment]
Thanks for opening @alankm 
I'll fix that ASAP. But if you have the bandwidth, please feel free to send a PR!
Many thanks!

**Comment by alankm** [comment]
What are your requirements in terms of breaking changes. I notice the release is tagged v1.0.0, which may imply that breaking changes are not acceptable. 

The reason I ask is because the cleanest way to fix this would be to change the field to a pointer.

**Comment by ricardozanini** [comment]
I agree using pointers instead is a better and cleaner approach. I'd rather not break the API, but the project is reasonably new. That way I think we can tolerate this break for now and release a `v1.1.0`.

**Comment by alankm** [comment]
The model code looks like it was generated. Was that a one-off? If I make changes to those files will they end up being overwritten?

**Comment by ricardozanini** [comment]
Yeah, the model code is generated, but we have a script to change it. For now, is a shell script "hack". We could elaborate more to add those kinds of changes.

**Comment by iwita** [comment]
Hi @alankm ,

Do you have some testcase for this?

**Comment by ricardozanini** [comment]
@iwita also fixed in #26
