### ISSUE TITLE
Add Workflow Compensation support

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/sdk-go#18]
Related to: https://github.com/serverlessworkflow/specification/pull/192/

We need to update the parsing methods to reflect this new feature from the spec side.

**Comment by tsurdilo** [comment]
https://github.com/serverlessworkflow/specification/pull/194 also changes the schema

**Comment by ricardozanini** [comment]
As soon as we merge these PRs, I'll update here. Thanks, @tsurdilo !

**Comment by ricardozanini** [comment]
Fixed in #26
