### ISSUE TITLE
Validation fails on "end" as an object with "compensate":true

### ISSUE THREAD

**Issue by ilewin** [serverlessworkflow/sdk-go#195]
**What happened**:
Unable to parse Workflow Definition with "end" key as an object with "compensate" set to true:
`"end": {
        "compensate": true
      }`
**What you expected to happen**:
Expected validation to pass
**How to reproduce it**:
Create a workflow definition with "end" statement as follows:
`"end": {
        "compensate": true
      }`
**Anything else we need to know?**:

**Environment**:
- Specification version used:
- 2.2.5

- Go version:

**Comment by ricardozanini** [comment]
Hey @ilewin do you mind sending a PR to fix this?

**Comment by cdavernas** [comment]
Closed as stale
