### ISSUE TITLE
Validation fails when transition.NextState is equal to currentState

### ISSUE THREAD

**Issue by Kshitiz1403** [serverlessworkflow/sdk-go#202]
**What happened**:
When doing state transitions, whenever the transition.NextState is defined as the currentState, the validation fails with the error `Error:Field validation for 'NextState' failed on the 'recursivestate' tag"`

**What you expected to happen**:
The validation should not fail when transitioning to the same state.

**How to reproduce it**:
Take for example this state

```json
{
  "name": "FineUser",
  "type": "operation",
  "actions": [
    {
      "functionRef": {
        "refName": "FineUserFn"
      }
    }
  ],
  "transition": "CallExternalAPI",
  "onErrors": [
    {
      "errorRef": "ServicesNotAvailable",
      "transition": "FineUser"
    },
    {
      "errorRef": "DefaultErrorRef",
      "transition": "Reject"
    }
  ]
}
```

The validation here fails for onErrors[0] since it is looking to transition to the state `FineUser` which seems to be not handled in the SDK.

One more example of this is - 

```json
{
  "name": "UserActionSignal",
  "type": "switch",
  "eventConditions": [
    {
      "eventRef": "fine_user",
      "transition": "FineUser"
    },
    {
      "eventRef": "reward_user",
      "transition": "RewardUser"
    }
  ],
  "metadata": {
    "moduleNameTag": "USER_REWARD_INPUT",
    "moduleStatusTag": "WAIT"
  },
  "timeouts": {
    "eventTimeout": "PT5S"
  },
  "defaultCondition": {
    "transition": "UserActionSignal"
  }
}
```
here, the default transition is configured as `UserActionSignal` but since the nextState is same as the currentState, the validator throws the error.

**Anything else we need to know?**:

**Environment**:
- SDK version: v2.2.5
- Go version: go1.20.14 darwin/arm64

**Comment by ricardozanini** [comment]
> The validation here fails for onErrors[0] since it is looking to transition to the state FineUser which seems to be not handled in the SDK.

So where's the state `FineUser`? I can't see it in your excerpt.

> here, the default transition is configured as UserActionSignal but since the nextState is same as the currentState, the validator throws the error.

So this will be an infinite loop, it's not valid.

**Comment by Kshitiz1403** [comment]
Handling for an infinite loop should be done from the application level. You can think of this as an "indefinite" retry which keeps on triggering this state till a certain result is achieved. 
Ideally Go SDK should not be the one making the call to allow/disallow using of infinite loop.

**Comment by Kshitiz1403** [comment]
> > The validation here fails for onErrors[0] since it is looking to transition to the state FineUser which seems to be not handled in the SDK.
> 
> So where's the state `FineUser`? I can't see it in your excerpt.
> 
> > here, the default transition is configured as UserActionSignal but since the nextState is same as the currentState, the validator throws the error.
> 
> So this will be an infinite loop, it's not valid.

On line 1 of example 1, the state is called "FineUser"

**Comment by ribeiromiranda** [comment]
@Kshitiz1403 A contribution in this scenario.

In the [Monitor Job Example](https://github.com/serverlessworkflow/specification/tree/0.8.x/examples#monitor-job-example), it has a sleep state, avoiding a loop that can cause many calls, in a very short time for the function.

**Comment by cdavernas** [comment]
Closed as stale
