### ISSUE TITLE
Add examples to handle Workflow Definitions as Kubernetes objects

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/sdk-go#30]
**What would you like to be added**:

Add examples of a CRD/CR being parsed by the SDK, so implementations based on Kubernetes could use it as inspiration to build their own.

**Why is this needed**:

Most of the Kubernetes environment is built around Golang. This example could be useful for implementations based on Kubernetes operators written in Golang.

**Comment by iwita** [comment]
Hello @ricardozanini. 
I could possibly help with that.

**Comment by ricardozanini** [comment]
@iwita go ahead :)

**Comment by ricardozanini** [comment]
Already handled by #146
