### ISSUE TITLE
YAML Workflow unmarshal panics in v2

### ISSUE THREAD

**Issue by jjrodenburg** [serverlessworkflow/sdk-go#33]
**What happened**:
We have a workflow yaml file that parses correctly in v1 and the Java SDK. When trying in v2, we get a panic inside the JSON Unmarshal code. Line 107 in workflow.go. Error: 
`panic: interface conversion: interface {} is []interface {}, not map[string]interface {}`

We parse using a call to `FromYAMLSource`.

**What you expected to happen**:
I expected the workflow to parse correctly.

**How to reproduce it**:
Use this YAML file and try to parse:
`id: CorgiFinder
name: Find a Corgi
description: Tries to find a corgi amongst chihuahas.
version: '0.1'
specVersion: '0.7'
start: DetectCorgiState
functions:
  - name: CorgiFinder||Detect
    operation: Detect
  - name: CorgiFinder||WoofAtCorgi
    operation: WoofAt
  - name: CorgiFinder||ScoopUpCorgi
    operation: Scoop
  - name:  CorgiFinder||DriveHomeCorgi
    operation: Drive
states:
  - name: DetectCorgiState
    type: operation
    actions:
      - name: DetectCorgiAction
        functionRef:
          refName: Detect
          arguments:
            - template: "${ .corgiBioInfo }"
          resultEventRef: CorgiDetectionResults
  - name: WoofAtCorgiState
    type: operation
    actions:
      - subFlowRef: WoofAtCorgi
  - name: ScoopUpCorgiState
    type: operation
    actions:
      - subFlowRef: ScoopUpCorgi
  - name: DriveHomeCorgiState
    type: operation
    actions:
      - subFlowRef: DriveHomeCorgi
`

Pastebin of yaml for better formatting: https://pastebin.com/W4Z5dp2S

**Anything else we need to know?**:

**Environment**:
- Specification version used:
0.7

- Go version:
go version go1.16.5 linux/amd64

**Comment by jjrodenburg** [comment]
Closing; we were able to get it to parse by making adjusting the action arguments logic:
`actions:
name: DetectCorgiAction
functionRef:
refName: Detect
arguments:
- template: "${ .corgiBioInfo }"
resultEventRef: CorgiDetectionResults`

to

`actions:
name: DetectCorgiAction
functionRef:
refName: Detect
arguments:
  template: "${ .corgiBioInfo }"
resultEventRef: CorgiDetectionResults`

**Comment by tsurdilo** [comment]
@ricardozanini ^^

**Comment by tsurdilo** [comment]
@jjrodenburg sorry just had time to look at this now - yes the arguments prop is object type not array. Glad you got it fixed!

I wanted to ask you - could you tell us about your involvement with our specification ? We are really interested to learning about users experiences, thoughts, and to get inputs. If you don't mind feel free to tell us here or hit me up on the CNCF slack (#serverless-workflow channel). Thanks!

**Comment by jjrodenburg** [comment]
@tsurdilo No worries! We're evaluating using the serverless workflow specification and this go sdk for an internal project. I'm liking it so far. I'll keep filing issues here if I encounter them.

**Comment by ricardozanini** [comment]
thanks @jjrodenburg @tsurdilo I had rough days the past week, I'll take a look at the issues this week and work on them.
