### ISSUE TITLE
OnError - how to tell whether Transition or End is defined (which to use)?

### ISSUE THREAD

**Issue by globalflea** [serverlessworkflow/sdk-go#47]
**What is the question**:
Since the OnError struct defines both Transition & End as struct and not pointers, how should i check if either is "defined" since i can't check for nil?

**Comment by ricardozanini** [comment]
We can change that to a `pointer` instead so you can check it for `nil`.

**Comment by globalflea** [comment]
actually, i am currently check if Transition.NextState is empty string to infer that Transition is not defined, which then implies it is End.  Not sure if this is the right approach.
