### ISSUE TITLE
Retry.Multiplier - no way to know if its undefined

### ISSUE THREAD

**Issue by globalflea** [serverlessworkflow/sdk-go#48]
in the struct Retry.Multiplier which is a floatstr.Float32OrString, there's no way to distinguish this field as not defined.  In the spec, this is supposed to be an optional field.  The default struct of Float32OrString will be Type Float and the zero value of FloatVal will be a 0.0 - which will be value if the workflow json/yaml left this out.

Unless i take Multiplier of 0 to be "not defined"?  in which case, the specs need to be updated to say zero value is not allowed or treated as not defined

**Comment by tsurdilo** [comment]
@globalflea agree, can you open issue in spec repo to add that multiplier smallest value should be 1. It makes no sense imo to have a 0 multiplier.

**Comment by ricardozanini** [comment]
@globalflea do you mind opening a PR to fix this?

**Comment by globalflea** [comment]
> @globalflea do you mind opening a PR to fix this?

I am new to open source and not too sure what you mean.. Are you asking me to open a Pull Request - and I fix it?

**Comment by tsurdilo** [comment]
@globalflea yeah we are community-driven project and community help on reporting and contributing to fixing bugs is something we rely on.
The level of contributions can of course vary depending on the person, but all help is more than welcome. 
If you don't feel comfortable with contributing code, that's perfectly fine, just note that in some cases contributing a fix yourself might get you unblocked faster.

**Comment by globalflea** [comment]
No problems, don't think I have any issues fixing the code. Since I am fairly new to this, patience on your part may be required.

**Comment by ricardozanini** [comment]
You did great :)
