### ISSUE TITLE
Access Events State

### ISSUE THREAD

**Issue by andresmijares** [serverlessworkflow/sdk-go#60]
**What happened**:

When implementing https://github.com/serverlessworkflow/sdk-go/blob/main/model/states.go#L64 , I cannot find any method that returns the `OnEvents` type, there's one for `OnErrors`, however, nothing for `OnEvents`

I wonder if this is the right behaviour and there's other way to have access to it, or just a bug.

The same applies for all other type of events, like ParallelState, InjectState, etc.

**What you expected to happen**:
To have access to the `onEvents` props from `State`

**How to reproduce it**:
Using the sample code:

```go
        wf, err := ParseWorkflow(state)
	if err != nil {
		log.Fatal(err.Error())
	}

	for _, state := range wf.States {
		eventState := state.OnEvents() // Method not available on the interface
	}
```

**Anything else we need to know?**:
No 

**Environment**:
- Specification version used: 2

- Go version: 1.18

**Comment by ricardozanini** [comment]
Hey @andresmijares, thanks for opening this issue!

Not all states have the `OnEvents` method (the SDK supports spec version 0.8). In this case, you need to convert to `EventState`: https://github.com/serverlessworkflow/sdk-go/blob/main/model/states.go#L138.

Can you try?

```go
	for _, state := range wf.States {
		eventState := state.(EventState).OnEvents() 
	}
```

I'm writing this from the top of my head, but you should be fine if you do the conversion. You may need to verify if the type is the `EventState` before converting.

**Comment by andresmijares** [comment]
Thank u @ricardozanini  

Interesting! it does the trick-sorta

I'm playing with this def https://github.com/serverlessworkflow/specification/tree/main/examples#workflow-definition

so I changed packages to use the `v1` instead of `v2`. The workflow definition `specVersion` is 0.8 as url shows.

when I try to parse, it doesn't like the `end: true`, if I remove it, i have access to it.

I'm cool working with the `0.8` spec, I just want to make sure it's all gucci :)

The whole code to reproduce is:

```go
import (
	"fmt"
	"log"

	"github.com/serverlessworkflow/sdk-go/model"
	"github.com/serverlessworkflow/sdk-go/parser"
)

var state = []byte(`
{
	"id": "eventbasedgreeting",
	"version": "1.0",
	"specVersion": "0.8",
	"name": "Event Based Greeting Workflow",
	"description": "Event Based Greeting",
	"start": "Greet",
	"events": [
	 {
	  "name": "GreetingEvent",
	  "type": "greetingEventType",
	  "source": "greetingEventSource"
	 }
	],
	"functions": [
	  {
		 "name": "greetingFunction",
		 "operation": "file://myapis/greetingapis.json#greeting"
	  }
	],
	"states":[
	  {
		 "name":"Greet",
		 "type":"event",
		 "onEvents": [{
			 "eventRefs": ["GreetingEvent"],
			 "eventDataFilter": {
				"data": "${ .greet }",
				"toStateData": "${ .greet }"
			 },
			 "actions":[
				{
				   "functionRef": {
					  "refName": "greetingFunction",
					  "arguments": {
						"name": "${ .greet.name }"
					  }
				   }
				}
			 ]
		 }],
		 "stateDataFilter": {
			"output": "${ .payload.greeting }"
		 },
                "end": true // doesnt work, removing this fixs it, but now I don't a way to finish the workflow
	  }
	]
	}`)


func ParseWorkflow(config []byte) (*model.Workflow, error) {
    workflow, err := parser.FromJSONSource(config)
    if err != nil {
        return nil, err
    }
    return workflow, nil
}

func main() {
	wf, err := ParseWorkflow(state)
	if err != nil {
		log.Fatal(err.Error())
	}

	for _, state := range wf.States {
		eventState := state.(*model.Eventstate)
		l := eventState.OnEvents[0]
		fmt.Println(l.ActionMode) // accesible
	}

}
```

**Comment by andresmijares** [comment]
@ricardozanini worked! thank you so much!
