### ISSUE TITLE
Access DatabaseSwitchState transitionDataCondition

### ISSUE THREAD

**Issue by andresmijares** [serverlessworkflow/sdk-go#62]
**What is the question**:

When trying to recreate [this example](https://github.com/tsurdilo/swtemporal/blob/232feea4fc8fa75686b2f19a0aa60f82f8e5bf5c/src/main/java/io/serverlessworkflow/demo/temporal/TemporalServerlessWorkflow.java#L149) I've found the following case...

Given this state definition

```json
{
    "name": "MakeApplicationDecision",
    "type": "switch",
    "dataConditions": [
	  {
		"condition": "$..[?(@.age >= 100)]",
		"transition": "ApproveApplication"
	 },
	 {
		"condition": "$..[?(@.age < 20)]",
		"transition": "RejectApplication"
	},
	{
		"condition": "$..[?(@.age > 50)]",
		"transition": "RejectApplication"
	}
  ],
	"defaultCondition": {
		"transition": "RejectApplication"
	}
}
```

How do I get access to the transition? assuming that:

```golang
     switchState, _ := state.(*model.DataBasedSwitchState)

    for _, dataCondition := range switchState.DataConditions {
            /*
               dataCondition is a DataCondition Interface which doesnt have access to next Transitions
           */
    }
```

I wonder if I should cast it somewhere to another interface, maybe [TransitionDataCondition](https://github.com/serverlessworkflow/sdk-go/blob/main/model/states.go#L476), what would be the ideal best action here??

So far I'm just casting the struct but it doesnt `feel` right, maybe?

```golang
  for _, dataCondition := range switchState.DataConditions {
          dCasted, ok := dataCondition.(*model.TransitionDataCondition)
	 if ok {
		nextState := dCasted.Transition.NextState 
	}
    }
```
Thank you!

**Comment by ricardozanini** [comment]
That's the correct way of doing that now, but we can improve this.

Instead of having `TransitionDataCondition`, we can introduce `Transition` to `DataConditions` directly. It's not a huge change and should be simple enough. @andresmijares do you mind sending a PR?

**Comment by andresmijares** [comment]
@ricardozanini sure thing! I will work on that during the weekend! thank you!
