### ISSUE TITLE
validate paas when switchState.dataConditions.transition is empty

### ISSUE THREAD

**Issue by lsytj0413** [serverlessworkflow/sdk-go#74]
**What happened**:

when remove the test example's https://github.com/serverlessworkflow/sdk-go/blob/main/parser/testdata/workflows/applicationrequest.json#L35 transition field，the ut still pass.

**What you expected to happen**:

- The unit test report failed

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Specification version used:

- Go version:

**Comment by ricardozanini** [comment]
@lsytj0413, are you submitting a PR for this? If not, I can provide the fix :)

**Comment by lsytj0413** [comment]
> @lsytj0413, are you submitting a PR for this? If not, I can provide the fix :)

I'm working on the fix for it，and the i will post the plan for discuss under the issue.

**Comment by lsytj0413** [comment]
For fix this issue, I proposal to replace `go-playground/validator/v10` with all custom validate function.

**How do we use validator:**

+ we only use five tags: required、omitempty、min、max、dive
+ use StructLevelFunc for addtional validate
+ the error message will contains struct & field names

From the above description it can be known that we only use a few feature in validator.

**disadvantage:**

In the implemention of workflow validation, i have noticed some scenarios which difficult to implement or mis-used:

+ invalid tag:
  + Example: `ActionExecTimeout string `json:"actionExecTimeout,omitempty" validate:"omitempty,min=1"``
  + This field is taged as omitempty, so it could be empty string(min = 0), and `min=1` is unneeded
+ It's hard to implement `ExpressionLang` validationg
  + This validation function depend on workflow's configuration, so it should paas-to all under StructLevelFunc
  + within validator framework, we only pass it in ctx
+ A lot Custom Validate function should be defined
  + such as []Retry，we should validate the retry's name is unique, so we must add Custom Type for validation function
  + `Jitter floatstr.Float32OrString `json:"jitter,omitempty" validate:"omitempty,min=0,max=1"``, is validate in invalid
+ Use `dive` on workflow.States cause a lot of validate error
  + For example, this will bring `Workflow.States[0].Timeouts.StateExecTimeout.Total`，`Workflow.States[0].BaseSwitchState.DefaultCondition.End.ContinueAs.WorkflowRef.WorkflowID` validate error

imo，the `go-playground/validator/v10` is powerful, but it brings some limitations, specifically we need a lot contextual validation. So i proposal to replace `go-playground/validator/v10` with self-implemented validate function.

cc @ricardozanini

**Comment by ricardozanini** [comment]
@lsytj0413 the proposal is good, but I think that even with the limited scope we are using, it still is something we didn't have to do for ourselves.

We can review the tags, add more appropriate ones/fix the existing and create custom validation within the framework.
