### ISSUE TITLE
map of AuthProperties pointers causes all parsed Workflows to have the same AuthProperties

### ISSUE THREAD

**Issue by calvinmclean** [serverlessworkflow/sdk-go#86]
**What happened**:
When parsing multiple Workflows with Bearer Auth, the tokens all end up the same.

**What you expected to happen**:
Each Workflow would have the bearer token specified in the Workflow YAML/JSON.

**How to reproduce it**:
Parse multiple Workflow files into Workflow models and print the pointer address of `workflow.Auth.Properties` and they will all be the same.

**Anything else we need to know?**:

**Environment**:
- Specification version used:
2.1.1 and 2.2.2
- Go version:
1.16

**Comment by spolti** [comment]
Hi @calvinmclean, thanks for reporting this, I'll be taking a look on this next week.

**Comment by calvinmclean** [comment]
Hi @spolti, thanks for your quick reply. I have a PR open now with a simple fix.
