### ISSUE TITLE
Provide a code style for IDEs

### ISSUE THREAD

**Issue by spolti** [serverlessworkflow/sdk-go#98]
Provide a standard code style profile so contributors can import it to help to keep a pattern across the code base.
For now, provides a profile for:

- IntelliJ / GoLand
- vscode

Note: This info needs to go into the CONTRIBUTIONS.md

**Comment by ricardozanini** [comment]
@spolti thanks! Are you going to do it? Please add to the CONTRIBUTIONS.md file too.

**Comment by spolti** [comment]
> @spolti thanks! Are you going to do it? Please add to the CONTRIBUTIONS.md file too.

Yes :)

**Comment by spolti** [comment]
@lsytj0413 @brlala @ricardozanini @davidesalerno 
hey guys, I would like to ask for some inputs here, for go, the code formatting is a little bit different when compared with other languages. 
e.g. for import, we have a few different tools that does it. gofmt, goimports.

So, instead of having a code style I was thinking on:


- import: default to goimports and add instruction on how to configure it on InjtelliJ/GoLand, VSCode, something else?
- provide a default editorconfig with only the go properties and explain how to import it to InjtelliJ/GoLand, VSCode, something else?
- add GHA lint checks (https://golangci-lint.run/usage/linters/), for now, maybe the default linters + gofmt and goheaders.
- ans last, add all these info in the CONTRIBUTORS_GUIDE.md 

wdyt?
